### ISSUE TITLE
Teleport to spawn working ~25% of the time

### ISSUE THREAD

**Issue by Kanawanagasaki** [juancarloscp52/Entropy#56] opened 2022-12-11 21:07 UTC
When I watched people play minecraft with an entropy mod on twitch or youtube teleport to spawn worked about 25% of the time. In most cases it simply kept player in place and just place a stone under.

**Comment by juancarloscp52** [comment] 2022-12-12 14:43
can you share some links of videos with timestaps, so I can look in detail? Thanks!

**Comment by Kanawanagasaki** [comment] 2022-12-12 18:13
https://www.twitch.tv/videos/1668378567?t=1h33m11s
https://www.twitch.tv/videos/1668378567?t=5h45m44s
https://youtu.be/R-dBAaj0Jj4?t=1356
https://www.twitch.tv/videos/1673224675?t=0h39m52s

**Comment by Kanawanagasaki** [comment] 2022-12-12 18:19
to be fair, everybody was playing on 1.19.2, i don't know will it happen on 1.19.3 or not

**Comment by Kanawanagasaki** [comment] 2022-12-18 08:41
Hmm, i saw so far only 2 people that play on 1.19.3 and both of them had working  teleport to spawn

https://www.twitch.tv/videos/1676712126?t=0h50m14s
https://youtu.be/t06n-Ozs6uM?t=2880

**Comment by Kanawanagasaki** [comment] 2022-12-18 08:42
So.. I guess it fixed itself? ¯\_(ツ)_/¯

**Comment by juancarloscp52** [comment] 2022-12-19 16:27
hmm, maybe they where using the 1.19.2 version before your fix in c60dda8a756080ba1dea34cd79495e0729de41db 
I'll do some extensive testing to make sure it is fixed in the 1.19.3 versions.

**Comment by juancarloscp52** [comment] 2022-12-21 16:50
It seems that the problem was solved in that version. Cannot reproduce after many tries

**Closed by juancarloscp52** 2022-12-21 16:50 UTC
