### ISSUE TITLE
No Attacking Allowed bug

### ISSUE THREAD

**Issue by Kanawanagasaki** [juancarloscp52/Entropy#105] opened 2023-03-03 12:03 UTC
If player was breaking blocks and "No Attacking Allowed" activated then effect will behave as if player clicked left mouse button and does not release it for duration of the effect.

https://clips.twitch.tv/GorgeousClearSlothHumbleLife--Sy8gpj-pfXxQoJp

**Comment by bl4ckscor3** [comment] 2023-03-03 12:35
I'll open a fix PR once the 1.19.4 branch is up. It's an easy fix, just adding `options.attackKey.setPressed(false);` during init. As a workaround, players can momentarily pause their game and the event will properly work.

**Comment by bl4ckscor3** [comment] 2023-03-20 17:38
This can be closed as the issue is fixed.

**Comment by juancarloscp52** [comment] 2023-03-20 18:28
Yep, forgot to follow through

**Closed by juancarloscp52** 2023-03-20 18:28 UTC
